server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:  #eureka 集群
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


zuul:   #路由映射
  prefix: /tidc
  ignored-services: "*"
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**


info:
  app.name: tidc-microcloud
  company.name: www.tidc.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

